{% set name = "django-cors-headers" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_cors_headers-{{ version }}.tar.gz
  sha256: 6c01a85cf1ec779a7bde621db853aa3ce5c065a5ba8e27df7a9f9e8dac310f4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - asgiref >=3.6
    - django >=3.2

test:
  imports:
    - corsheaders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ottoyiu/django-cors-headers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django app for handling the server headers required for Cross-Origin Resource Sharing (CORS)

  description: |
    A Django App that adds CORS (Cross-Origin Resource Sharing) headers to responses.

    Although JSON-P is useful, it is strictly limited to GET requests. 
    CORS builds on top of XmlHttpRequest to allow developers to make cross-domain requests, 
    similar to same-domain requests. Read more about it here <http://www.html5rocks.com/en/tutorials/cors/>.

  dev_url: https://github.com/ottoyiu/django-cors-headers

extra:
  recipe-maintainers:
    - rxm7706
    - lsetiawan
    - timsnyder
    - MichelML
