{% set name = "django-cors-headers" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_cors_headers-{{ version }}.tar.gz
  sha256: f9749c6410fe738278bc2b6ef17f05195bc7b251693c035752d8257026af024f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - django >=3.2

test:
  imports:
    - corsheaders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ottoyiu/django-cors-headers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django app for handling the server headers required for Cross-Origin Resource Sharing (CORS)

  description: |
    A Django App that adds CORS (Cross-Origin Resource Sharing) headers to responses.

    Although JSON-P is useful, it is strictly limited to GET requests. 
    CORS builds on top of XmlHttpRequest to allow developers to make cross-domain requests, 
    similar to same-domain requests. Read more about it here <http://www.html5rocks.com/en/tutorials/cors/>.

  dev_url: https://github.com/ottoyiu/django-cors-headers

extra:
  recipe-maintainers:
    - rxm7706
    - lsetiawan
    - timsnyder
    - MichelML
