{% set name = "django-cors-headers" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd6f4360f5246569c149dc1c40c907c191f1ec45551e10d2a2e2e68512652f78

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - django >=2.2

  run:
    - python >=3.6
    - django >=2.2

test:
  imports:
    - corsheaders

about:
  home: https://github.com/ottoyiu/django-cors-headers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django app for handling the server headers required for Cross-Origin Resource Sharing (CORS)

  description: |
    A Django App that adds CORS (Cross-Origin Resource Sharing) headers to responses.

    Although JSON-P is useful, it is strictly limited to GET requests. 
    CORS builds on top of XmlHttpRequest to allow developers to make cross-domain requests, 
    similar to same-domain requests. Read more about it here <http://www.html5rocks.com/en/tutorials/cors/>.

  dev_url: https://github.com/ottoyiu/django-cors-headers

extra:
  recipe-maintainers:
    - lsetiawan
    - timsnyder
    - MichelML
