{% set name = "django-cors-headers" %}
{% set version = "4.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_cors_headers-{{ version }}.tar.gz
  sha256: 6fdf31bf9c6d6448ba09ef57157db2268d515d94fc5c89a0a1028e1fc03ee52b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - asgiref >=3.6
    - django >=4.2

test:
  imports:
    - corsheaders
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ottoyiu/django-cors-headers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django app for handling the server headers required for Cross-Origin Resource Sharing (CORS)

  description: |
    A Django App that adds CORS (Cross-Origin Resource Sharing) headers to responses.

    Although JSON-P is useful, it is strictly limited to GET requests. 
    CORS builds on top of XmlHttpRequest to allow developers to make cross-domain requests, 
    similar to same-domain requests. Read more about it here <http://www.html5rocks.com/en/tutorials/cors/>.

  dev_url: https://github.com/ottoyiu/django-cors-headers

extra:
  recipe-maintainers:
    - rxm7706
    - lsetiawan
    - timsnyder
    - MichelML
